name: Tests
on:
  - pull_request

jobs:
  pytest:
    runs-on: ubuntu-latest

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.4.1
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip && pip install wheel --upgrade
          pip install numpy --upgrade
          pip install pytest --upgrade
          pip install tqdm --upgrade

      - name: Run tests
        run: python -m pytest tests
